markdown:  kramdown
kramdown:
    input: GFM
    extensions:
        - autolink
        - footnotes
        - smart
permalink: /:title/
url: http://Haoson.github.io
name: Haoson的博客
author: Weiqing Hao
qq: 1132113499
email: haoweiqinghaoson@gmail.com
weibo: 2068614947
github: Haoson
duoshuo: haoson
highlighter: rouge 
safe: true
paginate: 20
about: "我是Haoson，毕业于南京大学软件学院。目前在腾讯做游戏后台开发。\n\n这里是我的个人博客，主要记录技术相关的内容，切换到分类模式可以更快地找到感兴趣的内容，欢迎建议、拍砖。"
